name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -q

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build image
        run: docker build -t financetrack:ci .

      - name: Smoke test /health
        run: |
          cid=$(docker run -d -p 8000:8000 financetrack:ci)
          for i in {1..25}; do
            curl -fsS http://localhost:8000/health && ok=1 && break
            sleep 1
          done
          docker logs "$cid" --tail=80
          docker stop "$cid"
          test "$ok" = "1"
